macchiato/config/routes.rb
Rails.application.routes.draw do

  resources :shops

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

macchiato/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

macchiato/app/models/shop.rb
class Shop < ApplicationRecord
	include FriendlyId
	friendly_id :name, :use => [:slugged, :finders]
end

macchiato/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

macchiato/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

macchiato/app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def show
  	@shop = Shop.find_by name: params[:search]
  	if @shop == nil
  		redirect_to new_shop_path
  	end
  end

  def new

  end

  def create
  	@shop = Shop.new(shop_params)
  	@shop.save
  	redirect_to root_path
  end

  def new
  end


  private
  def shop_params
  	params.require(:shop).permit(:name, :address, :city, :result)
  end
end

macchiato/app/helpers/application_helper.rb
module ApplicationHelper
end

macchiato/app/helpers/home_helper.rb
module HomeHelper
end

macchiato/app/helpers/shops_helper.rb
module ShopsHelper
end

macchiato/app/views/home/index.html.erb
<h1>Welcome to Macchiato</h1>

<%= render 'shared/search' %>

macchiato/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Macchiato</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

macchiato/app/views/shared/_search.html.erb
<%= form_tag shop_path(:id), :method => 'get'  do %>
   <%= text_field_tag :search, params[:search]%>
   <%= submit_tag "Search", :name => nil  %>
<% end %>

macchiato/app/views/shops/new.html.erb
<h2>We don't have a result for that coffee place! Help us out and add it!</h2>

<%= form_for :shop, url: shops_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>
  <p>
    <%= f.label :city %><br>
    <%= f.text_area :city %>
  </p>
  <p>
    <%= f.label :result %><br>
    <%= f.text_area :result %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

macchiato/app/views/shops/show.html.erb
<h1>Results:</h1>

<h3>Name</h3>
<%= @shop.name %>
<h3>Address</h3>
<%= @shop.address %>
<%= @shop.city %>
<h1>This coffee place...<%= @shop.result %>ed</h1>

<p>Find another?</p>
<%= render 'shared/search' %>